# Generated by Django 5.0 on 2024-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tyoe',
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
