# Generated by Django 5.0 on 2024-05-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
